### ISSUE TITLE
Investigate JSCS crashing the server

### ISSUE THREAD

**Issue by Crawleyprint** [one-love/web-client#25]
`
[21:03:55] TypeError: Object.keys called on non-object  
    at Function.keys (native) `

    at NodeConfiguration.Configuration._throwNonCamelCaseErrorIfNeeded (/Users/mladen/repos/onelove/web-client/node_modules/gulp-jscs/node_modules/jscs/lib/config/configuration.js:396:12)
    at NodeConfiguration.Configuration.load (/Users/mladen/repos/onelove/web-client/node_modules/gulp-jscs/node_modules/jscs/lib/config/configuration.js:48:10)  

    at StringChecker.configure (/Users/mladen/repos/onelove/web-client/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:66:29)  

    at Checker.configure (/Users/mladen/repos/onelove/web-client/node_modules/gulp-jscs/node_modules/jscs/lib/checker.js:26:39)  

    at module.exports (/Users/mladen/repos/onelove/web-client/node_modules/gulp-jscs/index.js:31:11)
    at Gulp.gulp.task.gulp.src.pipe.scsslint.config (/Users/mladen/repos/onelove/web-client/tasks/development/checks.js:12:11)  

    at module.exports (/Users/mladen/repos/onelove/web-client/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)  

    at Gulp.Orchestrator._runTask (/Users/mladen/repos/onelove/web-client/node_modules/gulp/node_modules/orchestrator/index.js:273:3)

    at Gulp.Orchestrator._runStep (/Users/mladen/repos/onelove/web-client/node_modules/gulp/node_modules/orchestrator/index.js:214:10)

**Comment by therealklanni** [comment]
Any chance you can post your fix for this issue? I seem to be having the same problem in my project.

**Comment by Crawleyprint** [comment]
In my case, seems it wasn't a fix, but node/jscs version. However, it can be anything as problems disappeared when I moved to linux instead of mac os x, but I think it's one of those.
